config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: 'registrations' }
  resources :users, only: [:show, :edit, :update] do
    resources :workouts
  end

  resources :workouts, only: [:show] do 
    resources :focuses, only: [:edit, :update, :destroy]
  end

  resources :favorites, only: [:create, :destroy]
  
  get 'admin' => 'admin#index'
  get 'admin/most-workouts' => 'admin#active'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout
end

app/models/focus.rb
class Focus < ActiveRecord::Base

  has_many :focus_workouts
  has_many :workouts, through: :focus_workouts

  validates_presence_of :name, :description, :duration
  
end

app/models/focus_workout.rb
class FocusWorkout < ActiveRecord::Base

  belongs_to :focus
  belongs_to :workout
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  enum role: [:user, :admin]
  has_many :workouts
  has_many :focuses, through: :workouts
  has_many :favorites

  after_initialize :set_user_role

  def set_user_role
    self.role ||= :user
  end

  def self.most_active
    user = self.all.max_by { |u| u.workouts.count }
  end

  def self.from_omniauth(auth)  
    #raise auth.inspect
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :focus_workouts
  has_many :focuses, through: :focus_workouts
  has_many :favorites

  validates_presence_of :name, :description, :duration

  def focuses_attributes=(focuses_hashes)
    focuses_hashes.each do |index, focus_attributes|
      if focus_attributes[:name].present?
        focus = Focus.find_or_create_by(focus_attributes)
        if !self.focuses.include?(focus)
          self.focus_workouts.build(focus: focus)
        end
      end
    end
  end
  #   focuses_hashes.each do |key, values|
  #     if values[:name].present?
  #       self.focuses << Focus.find_or_create_by(values) if !self.focuses.select { |f| f.name == values[:name]}
  #     end
  #   end
  # end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    if current_user.role == 'admin'
      @workouts = Workout.all 
      @users = User.all
      @user = current_user
    else
      redirect_to root_path
    end
  end

  def active
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

    def user_not_authorized
    flash[:error] = "Sorry! You are not authorized to perform that action."
    redirect_to root_path
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    #raise params.inspect
    @favorite = Favorite.create(favorite_params)
    redirect_to user_workout_path(@favorite.workout.user, @favorite.workout)
  end


  private 

    def favorite_params
      params.require(:favorite).permit(:user_id, :workout_id)
    end

end

app/controllers/focuses_controller.rb
class FocusesController < ApplicationController
  before_action :set_focus, only: [:edit, :update, :destroy]
  before_action :set_workout, only: [:edit, :update]

  def edit
  end

  def update
    if @focus.update(focus_params)
      redirect_to user_workout_path(current_user, params[:workout_id])
    else
      render :edit
    end
  end

  def destroy
    @focus.destroy
    redirect_to user_workout_path(current_user, params[:workout_id])
  end


  private 

    def set_focus
      @focus = Focus.find_by(id: params[:id])
    end

    def set_workout
      @workout = Workout.find_by(id: params[:workout_id])
    end

    def focus_params
      params.require(:focus).permit(:name, :description, :duration)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      @workouts = Workout.all
    else
      render 'static/index' 
    end
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

    def set_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :bio)
    end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_user, only: [:index, :new, :create, :edit, :update]
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @workouts = @user.workouts
  end

  def new
    if current_user.id == params[:user_id].to_i
      @workout = Workout.new 
    else 
      redirect_to new_user_workout_path(current_user)
    end
  end

  def create
    @workout = @user.workouts.build(workout_params)
    if @workout.save
      redirect_to user_workout_path(@user, @workout)
    else
      render :new
    end
  end

  def show
    @favorite = Favorite.new
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to user_workout_path(@user, @workout)
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to user_workouts_path(current_user)
  end


  private

    def set_user
      @user = User.find_by(id: params[:user_id])
    end

    def set_workout
      @workout = Workout.find_by(id: params[:id])
    end

    def authorize_user
      authorize @workout
    end

    def workout_params
      params.require(:workout).permit(:name, :description, :private, :duration, focus_ids:[], focuses_attributes: [:name, :description, :duration])
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_or_add_bio(user)
    if user.bio.present?
      user.bio
    elsif  user == current_user
      link_to "Add Bio", edit_user_path(user)
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/focuses_helper.rb
module FocusesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper

  def current_user_workout?
    current_user == @workout.user || current_user.role == 'admin'
  end

end

app/views/focuses/edit.html.erb
Edit the Segment:

<%= render partial: '/workouts/errors', locals: { record: @focus } %>

<%= form_for ([@workout, @focus]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :description %>
  <%= f.text_field :description %><br />
  <%= f.label "Number of Minutes" %>
  <%= f.number_field :duration %><br />
  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
<h3>Popular Workouts</h3>
<ul>
  <% @workouts.each do |workout| %>
    <% if !workout.private %>
      <li><%= link_to workout.name, user_workout_path(workout.user, workout) %> by <%= link_to workout.user.username, user_workouts_path(workout.user) %></li>
      <%= workout.description %>
    <% end %>
  <% end %>
</ul>


<%= link_to "Create a new workout!", new_user_workout_path(current_user), class: 'btn btn-primary' %>

app/views/users/edit.html.erb
Change your details:
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br />
  <%= f.label :username %>
  <%= f.text_field :username %><br />
  <%= f.label :bio %>
  <%= f.text_area :bio %><br />
  <%= f.submit "Update" %>
<% end %>

Update your email/password <%= link_to "here", edit_user_registration_path %>.

app/views/users/show.html.erb
Hello <%= @user.first_name %><br />
<%= display_or_add_bio(@user) %><br />
Username: <%= @user.username %><br />
<%= link_to "Edit Profile", edit_user_path(@user) %>

app/views/workouts/_errors.html.erb
<% if record.errors.any? %>
 <div id="error_explanation" class="alert alert-danger" role="alert">
   <h2>Errors:</h2>
   <ul>
   <% record.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

app/views/workouts/_form.html.erb
<%= render partial: '/workouts/errors', locals: { record: @workout } %>

<%= form_for([@user, @workout]) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :duration %>
    <%= f.text_field :duration, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Check if you'd like to keep this workout private" %>
    <%= f.check_box :private %>
  </div>

  <h3>Add a segment to this workout:</h3>
  <div class="form-group">
    <%= f.collection_check_boxes :focus_ids, Focus.all, :id, :name %>
  </div>

  <%= f.fields_for :focuses, @workout.focuses.build do |focus| %>
    <div class="form-group">
      <%= focus.label :name %>
      <%= focus.text_field :name %>
    </div>

    <div class="form-group">
      <%= focus.label :description %>
      <%= focus.text_field :description %>
    </div>

    <div class="form-group">
      <%= focus.label "Number of Minutes" %>
      <%= focus.number_field :duration %>
    </div>
  <% end %>
<%= f.submit %>
<% end %>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>
<%= render 'form' %>

app/views/workouts/index.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %> @<%= @user.username %></h1>
<%= display_or_add_bio(@user) %>
<h3>Workouts</h3>
<ul>
  <% @workouts.each do |workout| %>
    <% if policy(workout).edit? %>
      <li><%= link_to workout.name, user_workout_path(workout.user, workout) %>
      <% if workout.private %>
        (private)
      <% end %></li>
    <% elsif !workout.private %>
      <li><%= link_to workout.name, user_workout_path(workout.user, workout) %></li>
    <% end %>
  <% end %>
</ul>

<h3>Favorites</h3>
<ul>
  <% @user.favorites.each do |favorite| %>
    <li><%= link_to favorite.workout.name, user_workout_path(favorite.workout.user, favorite.workout) %> 
  <% end %>
</ul>

<% if current_user == @user %>
  <%= link_to "Create a new workout!", new_user_workout_path(current_user), class: 'btn btn-primary' %><br>
  <%= link_to "Edit Profile", edit_user_path(@user) %>
<% end %>

app/views/workouts/new.html.erb
<h1>Create a Workout</h1>
<%= render 'form' %>

app/views/workouts/show.html.erb
<h1><%= @workout.name %></h1>
<%= form_for(@favorite) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :workout_id, value: @workout.id %>
  <%= f.submit "Add to Favorites" %>
<% end %><br />

<p>by <%= link_to @workout.user.username, user_workouts_path(@workout.user) %> </p>
<p><%= @workout.description %></p>
<p>Duration: <%= @workout.duration %></p>
<% if current_user_workout? %>
  <%= link_to "Edit", edit_user_workout_path(@workout.user, @workout), class: 'btn btn-sm btn-info' %>  <%= link_to "Delete Workout", user_workout_path(@workout.user, @workout), method: :delete, class: 'btn btn-sm btn-danger' %><br />
<% end %>

<h3>Segments of this workout</h3>
<% @workout.focuses.each do |focus| %>
  <p><%= focus.name %></p>
  <p><%= focus.description %></p>
  <p>This will take about <%= focus.duration %> minutes.</p>
  <% if current_user_workout? %>
    <%= link_to "Edit", edit_workout_focus_path(@workout, focus), class: 'btn btn-xs btn-info' %> <%= link_to "Delete Focus", workout_focus_path(@workout, focus), method: :delete, class: 'btn btn-xs btn-danger' %><br />
  <% end %>
  -------------------- <br />
<% end %>

<%= link_to "Add a segment to this workout", edit_user_workout_path(@workout.user, @workout) if current_user_workout? %>