config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: 'registrations' }
  resources :users, only: [:show, :edit, :update] do
    resources :workouts
  end

  resources :workouts, only: [:show] do 
    resources :focuses, only: [:edit, :update, :destroy]
  end

  resources :favorites, only: [:create, :destroy]
  
  get 'admin' => 'admin#index'
  get 'admin/most-workouts' => 'admin#active'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout
end

app/models/focus.rb
class Focus < ActiveRecord::Base

  has_many :focus_workouts
  has_many :workouts, through: :focus_workouts

  validates_presence_of :name, :description, :duration
  
end

app/models/focus_workout.rb
class FocusWorkout < ActiveRecord::Base

  belongs_to :focus
  belongs_to :workout
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  enum role: [:user, :admin]
  has_many :workouts
  has_many :focuses, through: :workouts
  has_many :favorites

  after_initialize :set_user_role

  def set_user_role
    self.role ||= :user
  end

  def self.most_active
    user = self.all.max_by { |u| u.workouts.count }
  end

  def self.from_omniauth(auth)  
    #raise auth.inspect
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :focus_workouts
  has_many :focuses, through: :focus_workouts
  has_many :favorites

  validates_presence_of :name, :description, :duration

  def focuses_attributes=(focuses_hashes)
    focuses_hashes.each do |index, focus_attributes|
      if focus_attributes[:name].present?
        focus = Focus.find_or_create_by(focus_attributes)
        if !self.focuses.include?(focus)
          self.focus_workouts.build(focus: focus)
        end
      end
    end
  end
  #   focuses_hashes.each do |key, values|
  #     if values[:name].present?
  #       self.focuses << Focus.find_or_create_by(values) if !self.focuses.select { |f| f.name == values[:name]}
  #     end
  #   end
  # end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    if current_user.role == 'admin'
      @workouts = Workout.all 
      @users = User.all
      @user = current_user
    else
      redirect_to root_path
    end
  end

  def active
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

    def user_not_authorized
    flash[:error] = "Sorry! You are not authorized to perform that action."
    redirect_to root_path
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    #raise params.inspect
    @favorite = Favorite.create(favorite_params)
    redirect_to user_workout_path(@favorite.workout.user, @favorite.workout)
  end


  private 

    def favorite_params
      params.require(:favorite).permit(:user_id, :workout_id)
    end

end

app/controllers/focuses_controller.rb
class FocusesController < ApplicationController
  before_action :set_focus, only: [:edit, :update, :destroy]
  before_action :set_workout, only: [:edit, :update]

  def edit
  end

  def update
    if @focus.update(focus_params)
      redirect_to user_workout_path(current_user, params[:workout_id])
    else
      render :edit
    end
  end

  def destroy
    @focus.destroy
    redirect_to user_workout_path(current_user, params[:workout_id])
  end


  private 

    def set_focus
      @focus = Focus.find_by(id: params[:id])
    end

    def set_workout
      @workout = Workout.find_by(id: params[:workout_id])
    end

    def focus_params
      params.require(:focus).permit(:name, :description, :duration)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      @workouts = Workout.all
    else
      render 'static/index' 
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

    def set_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :bio)
    end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_user, only: [:index, :new, :create, :edit, :update]
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @workouts = @user.workouts
  end

  def new
    if current_user.id == params[:user_id].to_i
      @workout = Workout.new 
    else 
      redirect_to new_user_workout_path(current_user)
    end
  end

  def create
    @workout = @user.workouts.build(workout_params)
    if @workout.save
      redirect_to user_workout_path(@user, @workout)
    else
      render :new
    end
  end

  def show
    @favorite = Favorite.new
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to user_workout_path(@user, @workout)
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to user_workouts_path(current_user)
  end


  private

    def set_user
      @user = User.find_by(id: params[:user_id])
    end

    def set_workout
      @workout = Workout.find_by(id: params[:id])
    end

    def authorize_user
      authorize @workout
    end

    def workout_params
      params.require(:workout).permit(:name, :description, :private, :duration, focus_ids:[], focuses_attributes: [:name, :description, :duration])
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_or_add_bio(user)
    if user.bio.present?
      user.bio
    elsif  user == current_user
      link_to "Add Bio", edit_user_path(user)
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/focuses_helper.rb
module FocusesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper

  def current_user_workout?
    current_user == @workout.user || current_user.role == 'admin'
  end

end

app/views/admin/active.html.erb
<p>The most active user is <%= link_to User.most_active.username, user_workouts_path(User.most_active) %>: <%= User.most_active.workouts.count %> workouts.</p>

app/views/admin/index.html.erb
<h1>Hello <%= @user.first_name %></h1>

<p><%= link_to "Click for the most active user", admin_most_workouts_path %></p>


<p>Here's the latest activity:<p>
<ul>
  <% @workouts.reverse_each do |workout| %>
      <li><%= link_to workout.name, user_workout_path(workout.user, workout) %> by <%= link_to workout.user.username, user_workouts_path(workout.user) %></li>
      <%= workout.description %>
  <% end %>
</ul>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">CodeWorkouts</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to current_user.username, user_workouts_path(current_user) %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% if current_user.role == 'admin' %>
            <li><%= link_to "Admin Panel", admin_path %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Code Workouts</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
  <body>

  <%= render 'layouts/navigation' %>

  <div class="container-fluid">

    <% flash.each do |name, msg| %>
      <% if name == "error" %>    
        <div class="alert alert-danger" role="alert"><%= msg %></div>
      <% elsif name == "notice" %>
        <div class="alert alert-success" role="alert"><%= msg %></div>
      <% else %>
        <div class="alert alert-info" role="alert"><%= msg %></div>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>